project jv-stream-github-practice is ready for a code review
mate-academy/jv-stream-github-practice pull request #1013
Opened 2024-02-21 19:45 UTC by misterSokor

2024-02-22 10:17 UTC, MentorMA requested changes

2024-02-22 10:17 UTC, MentorMA commented on src/main/java/practice/CandidateValidator.java
> +        return endYear - startYear;
I can`t see constants for strings and numbers

2024-02-22 10:17 UTC, MentorMA commented on src/main/java/practice/StreamPractice.java
> +                //s -> Sting["5", "30", "100"]
```suggestion
```

2024-02-22 10:17 UTC, MentorMA commented on src/main/java/practice/StreamPractice.java
> +                //s -> Sting["5", "30", "100"]
It`s redundant information

2024-02-22 10:17 UTC, MentorMA commented on src/main/java/practice/StreamPractice.java
> +        return personStream.toList();
dont use map method here, just try to use collect()

2024-02-23 12:18 UTC, kerrrusha requested changes

2024-02-24 11:37 UTC, MentorMA requested changes

2024-02-24 11:37 UTC, MentorMA commented on src/main/java/practice/CandidateValidator.java
> +                && "Ukrainian".equals(candidate.getNationality())
String save to constant

2024-02-24 11:37 UTC, MentorMA commented on src/main/java/practice/StreamPractice.java
> +                            || (sex == Person.Sex.MAN && age >= fromAge && age <= maleToAge);
Try to simplify realisation of method filter, you don`t need return inside it

2024-02-24 11:37 UTC, MentorMA commented on src/main/java/practice/StreamPractice.java
> +                .map(Candidate:: getName)
```suggestion
                .map(Candidate::getName)
```

2024-02-28 10:00 UTC, Rommelua requested changes

2024-02-28 10:00 UTC, Rommelua commented on src/main/java/practice/StreamPractice.java
> +        return false;
```suggestion
        return sex == Person.Sex.WOMAN && age >= fromAge && age <= femaleToAge
            || sex == Person.Sex.MAN && age >= fromAge && age <= maleToAge;
```

2024-02-29 11:52 UTC, MentorMA requested changes

2024-02-29 11:52 UTC, MentorMA commented on src/main/java/practice/StreamPractice.java
> +                || sex == Person.Sex.MAN && age >= fromAge && age <= maleToAge;
Better write initialization of Predicar and use in filter

2024-02-29 11:52 UTC, MentorMA commented on src/main/java/model/Person.java
> +            + ", cats that " + name + " has: " + cats;
Don`t change this

2024-02-29 11:52 UTC, MentorMA commented on src/main/java/model/Cat.java
> +            + ", age: " + age;
Don`t change this

2024-03-01 11:39 UTC, kerrrusha approved these changes

2025-08-13 04:21 UTC, closed without merging