mvn clean package done
mate-academy/jv-stream-github-practice pull request #1026
Opened 2024-03-09 12:47 UTC by qreqit

2024-03-09 13:42 UTC, MentorMA requested changes

2024-03-09 13:42 UTC, MentorMA commented on src/main/java/practice/CandidateValidator.java
> +        int yearsInUkr = Integer.parseInt(years[1]) - Integer.parseInt(years[0]);
Magic numbers

2024-03-09 13:42 UTC, MentorMA commented on src/main/java/practice/StreamPractice.java
> +                .map(cat -> cat.getName())
Here you can use method reference

2024-03-10 10:27 UTC, MentorMA requested changes

2024-03-10 10:27 UTC, MentorMA commented on src/main/java/practice/CandidateValidator.java
> +        int yearsInUkr = Integer.parseInt(years[1]) - Integer.parseInt(years[0]);
Not fixed

2024-03-10 10:27 UTC, MentorMA commented on src/main/java/practice/CandidateValidator.java
> +        int yearsInUkr = Integer.parseInt(years[1]) - Integer.parseInt(years[0]);
Save it to constant

2024-03-11 18:17 UTC, kerrrusha approved these changes

2026-02-12 10:15 UTC, closed without merging