Implement StreamPractice, CandidateValidator classes
mate-academy/jv-stream-github-practice pull request #1168
Opened 2024-10-21 22:14 UTC by skotsurskiy

2024-10-21 22:14 UTC, mateacademy-ai-mentor requested changes
There are a few critical issues that need to be addressed before we can proceed. Specifically, the condition for checking the required living years needs to be corrected to ensure proper functionality. Additionally, using '==' for Enum comparison is recommended for efficiency. Please address these issues, and feel free to reach out if you need any help! 😊 Keep up the good work!

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-10-21 22:14 UTC, mateacademy-ai-mentor commented on src/main/java/practice/CandidateValidator.java
> +                && candidate.getNationality().equals("Ukrainian")
Consider using a constant for the string "Ukrainian" to improve code readability and maintainability.

2024-10-21 22:14 UTC, mateacademy-ai-mentor commented on src/main/java/practice/CandidateValidator.java
> +        return secondDate - firstDate > REQUIRED_LIVING_YEARS;
The condition should be '>= REQUIRED_LIVING_YEARS' instead of '>' to ensure the candidate has lived for at least the required number of years.

2024-10-21 22:14 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                .map(s -> Arrays.stream(s.split("[^-0-9]+")).toList())
Consider using a single map operation instead of a sequence of map and flatMap operations. You can directly split the string and parse integers in one step.

2024-10-21 22:14 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                .mapToObj(i -> i % EVEN_CHECK == ODD_ADJUSTMENT ? numbers.get(i) - ODD_ADJUSTMENT : numbers.get(i))
This line contains a ternary operation that could be simplified by using a single map operation. Consider using a single map operation to adjust the values based on their index.

2024-10-21 22:14 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                        && person.getSex() == Person.Sex.MAN;
When comparing Enum values, it's generally better to use '==' instead of 'equals()'. This is because Enums are singletons and '==' is more efficient.

2024-10-21 22:14 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                        || (person.getSex() == Person.Sex.MAN
When comparing Enum values, it's generally better to use '==' instead of 'equals()'. This is because Enums are singletons and '==' is more efficient.

2024-10-21 22:30 UTC, mateacademy-ai-mentor approved these changes
Great job on implementing the CandidateValidator class! 🎉 The use of constants and the Predicate interface is commendable, and the helper method enhances readability. While there are some areas for improvement, such as simplifying complex logical expressions and optimizing Enum comparisons, these do not hinder the overall functionality. Keep these suggestions in mind for future projects to refine your skills further. Remember, learning from feedback is key to growth. Keep up the good work! 🚀

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-10-21 22:30 UTC, mateacademy-ai-mentor commented on src/main/java/practice/CandidateValidator.java
> +                && candidate.getNationality().equals(REQUIRED_NATIONALITY)
Consider using '==' for comparing Enum values instead of 'equals()'. This is generally more efficient and is the recommended approach for Enum comparison.

2024-10-21 22:30 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                        ? numbers.get(i) - ODD_ADJUSTMENT : numbers.get(i))
The expression for adjusting numbers at odd positions is correct, but it could be simplified by using a single map operation instead of mapToObj followed by mapToInt. This would align with the checklist item: 'Where possible try to use single map operation instead of sequence of them.'

2024-10-21 22:30 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                        && person.getSex() == Person.Sex.MAN;
When comparing Enum values, it's generally better to use '==' instead of 'equals()'. This is because Enums are singletons, and '==' is more efficient and null-safe. This aligns with the checklist item: 'Pay attention to what is a better way to compare Enum values: equals() vs == ?'

2024-10-21 22:30 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                        && person.getAge() <= maleToAge));
The logical expression here is a bit complex due to the use of both '&&' and '||'. Consider simplifying or restructuring it for better readability, possibly by creating a custom Predicate as suggested in the checklist: 'If you have a long boolean expression you may create your own implementation of Predicate and use it in your filter.'

2024-10-22 07:57 UTC, Sanderfuck requested changes

2024-10-22 07:57 UTC, Sanderfuck commented on src/main/java/practice/CandidateValidator.java
> +        int secondDate = Integer.parseInt(periodsSplit[1]);
magic numbers

2024-10-22 07:57 UTC, Sanderfuck commented on src/main/java/practice/StreamPractice.java
> +                -> new RuntimeException("Can't get min value from list: " + numbers));
you should use only stream, don`t save min variable

2024-10-22 07:57 UTC, Sanderfuck commented on src/main/java/practice/StreamPractice.java
> +                .mapToInt(n -> n)
here you don`t need 2 methods map

2024-10-22 07:57 UTC, Sanderfuck commented on src/main/java/practice/StreamPractice.java
> +        return average.orElseThrow(NoSuchElementException::new);
The same

2024-10-22 07:57 UTC, Sanderfuck commented on src/main/java/practice/StreamPractice.java
> +        };
better use lambda here instead of anonymous class

2024-10-22 07:57 UTC, Sanderfuck commented on src/main/java/practice/StreamPractice.java
> +                .map(Cat::getName)
too many methods map

2024-10-25 07:01 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2024-10-25 07:01 UTC, liliia-ponomarenko commented on src/main/java/practice/StreamPractice.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```
I guess you can simplify it 😉

2024-10-26 16:39 UTC, Elena-Bruyako approved these changes

2025-09-27 08:03 UTC, closed without merging