Pull_request_1
mate-academy/jv-stream-github-practice pull request #1178
Opened 2024-10-29 14:45 UTC by RVoinahii

Implement stream-based methods from processing data from lists of string, integers, and custom objects.

2024-10-29 14:46 UTC, mateacademy-ai-mentor requested changes
****

Thank you for your hard work on this project! 😊 While your code meets most of the task requirements, there are a few critical issues that need to be addressed before we can approve the pull request:

1. **Magic Numbers and Strings**: In the `CandidateValidator` class, replace magic numbers (e.g., `35` for age and `10` for years in Ukraine) with named constants to improve code readability and maintainability.

2. **Exception Message Format**: In the `findMinEvenNumber` method, ensure the exception message is formatted as `"Can't get min value from list: " + numbers`. This will help in debugging and understanding the context of the error.

3. **Stream Method Chaining**: For better readability, consider calling each new method from a new line in the stream. This will make your code easier to read and maintain.

4. **Error Handling in `findMinEvenNumber`**: Add error handling to manage cases where strings might not be in the expected format or contain non-numeric values. This will prevent runtime errors and improve the robustness of your code.

5. **Parsing Periods in `CandidateValidator`**: Ensure that the parsing logic for `candidate.getPeriodsInUkr()` is robust and can handle different formats or multiple periods. Adding validation or error handling will prevent incorrect results.

Please address these issues to ensure your code fully complies with the task requirements. Keep up the great work, and I look forward to seeing your improvements! 🚀

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

🔄 Fix the issues, commit the changes, and then re-request my review using the `Re-request review` button in the Reviewers tab.

2024-10-29 14:46 UTC, mateacademy-ai-mentor commented on src/main/java/practice/CandidateValidator.java
> +        int endYear = Integer.parseInt(yearsInUkr[1]);
The code assumes that `candidate.getPeriodsInUkr()` returns a string in the format 'startYear-endYear'. If the format is different or if there are multiple periods, this parsing will fail or give incorrect results. Consider adding validation or error handling to ensure the format is correct before parsing.

2024-10-29 14:46 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                        .map(Integer::parseInt))
The `findMinEvenNumber` method assumes that each string in the list can be split into integers. Consider adding error handling to manage cases where the strings might not be in the expected format or contain non-numeric values.

2024-10-29 14:46 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                .mapToDouble(i -> (i % 2 != 0 ? numbers.get(i) - 1 : numbers.get(i)))
In the `getOddNumsAverage` method, ensure that the subtraction of 1 from elements at odd positions does not result in negative numbers if your business logic requires non-negative numbers.

2024-10-29 14:46 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                        person.getAge() >= fromAge && person.getAge() <= femaleToAge)
The ternary operator in `getWorkablePeople` is correctly used, but ensure that the logic for age limits is clear and correctly implemented for both men and women.

2024-10-29 15:08 UTC, mateacademy-ai-mentor approved these changes
Great job on implementing the solution! 🎉 Your code meets most of the task requirements and constraints, which is a fantastic achievement. However, there are a few critical issues that need attention:

1. **Ternary Operator Usage**: In the `getWorkablePeople` method, the ternary operator is used incorrectly. Ensure that the condition is enclosed in parentheses for proper evaluation.

2. **Years Calculation in Ukraine**: The logic for calculating the years spent in Ukraine needs adjustment. Instead of checking if any single period meets the requirement, sum up all periods to ensure the total time spent is sufficient.

These issues are important for the functionality of your code, so please review the comments and make necessary improvements. Addressing these will help you avoid similar problems in the future. Keep up the good work and continue learning from your experiences! 🚀

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-10-29 15:20 UTC, ahoienko requested changes
Nice, left some some comments

2024-10-29 15:20 UTC, ahoienko commented on src/main/java/practice/CandidateValidator.java
> +                int endYear = Integer.parseInt(years[1].trim());
Magic numbers

2024-10-29 15:20 UTC, ahoienko commented on src/main/java/practice/CandidateValidator.java
> +            String[] years = period.trim().split("-");
Please add string literals to constants

2024-10-29 15:20 UTC, ahoienko commented on src/main/java/practice/CandidateValidator.java
> +                && candidate.getNationality().equals("Ukrainian")
Please add string literals to constants

2024-10-29 15:20 UTC, ahoienko commented on src/main/java/practice/StreamPractice.java
> +                .filter(number -> number % 2 == 0)
Code duplication

2024-10-29 15:20 UTC, ahoienko commented on src/main/java/practice/StreamPractice.java
> +        final CandidateValidator candidateValidator = new CandidateValidator();
What is the reason to create this object each time validateCandidates method is called

2024-10-29 15:20 UTC, ahoienko commented on src/main/java/practice/StreamPractice.java
> +                        person.getAge() >= fromAge && person.getAge() <= femaleToAge)
I suggest you to move this logic to separate method to make this core more readable

2024-10-29 15:20 UTC, ahoienko commented on src/main/java/practice/StreamPractice.java
> +                .filter(number -> number % 2 == 0)
```suggestion
        return numbers.stream()
                .flatMap(list -> Arrays.stream(list.split(",")))
                .mapToInt(Integer::parseInt)
                .filter(....
```

2024-10-29 15:20 UTC, ahoienko commented on src/main/java/practice/CandidateValidator.java
> +                && hasRequiredYearsInUkraine(candidate.getPeriodsInUkr());
```suggestion
String[] yearFromTo = candidate.getPeriodsInUkr().split(SEPARATE);
        int period = Integer.parseInt(yearFromTo[YEAR_TO])
                - Integer.parseInt(yearFromTo[YEAR_FROM]);
                
          return candidate.getAge() >= VALID_AGE && candidate.getNationality().equals(NATIONALITY)
                && period >= VALID_PERIOD && candidate.isAllowedToVote();
```

2024-10-30 13:23 UTC, Elena-Bruyako requested changes

2024-10-30 13:23 UTC, Elena-Bruyako commented on src/main/java/practice/StreamPractice.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-10-30 13:23 UTC, Elena-Bruyako commented on src/main/java/practice/StreamPractice.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-10-30 13:23 UTC, Elena-Bruyako commented on src/main/java/practice/StreamPractice.java
> +    private boolean isWorkable(Person person, int fromAge, int femaleToAge, int maleToAge) {
all private methods should be placed only after public methods

2024-10-30 13:23 UTC, Elena-Bruyako commented on src/main/java/practice/StreamPractice.java
> +                .filter(CandidateValidator.VALIDATE)
```suggestion
                .filter(new CandidateValidator())
```

2024-10-30 13:23 UTC, Elena-Bruyako commented on src/main/java/practice/StreamPractice.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-10-30 13:23 UTC, Elena-Bruyako commented on src/main/java/practice/CandidateValidator.java
> +    public static final Predicate<Candidate> VALIDATE = new CandidateValidator();
```suggestion
```

2024-10-30 14:31 UTC, Elena-Bruyako approved these changes

2025-06-06 12:03 UTC, closed without merging