implemented base logic
mate-academy/jv-stream-github-practice pull request #1192
Opened 2024-11-16 20:04 UTC by VasylAzarov

2024-11-16 20:05 UTC, mateacademy-ai-mentor requested changes
Thank you for your hard work on this pull request! 😊 While your code meets many of the task requirements, there are a few critical issues that need to be addressed before we can approve it:

1. **Logical Error in `getWorkablePeople` Method**: The filtering condition for workable people seems incorrect. It should check if the person's age is less than or equal to `maleToAge` for men and `femaleToAge` for women, instead of greater than or equal to these ages. This affects the core functionality of the method.

2. **Inconsistency in `getOddNumsAverage` Method**: The logic for averaging odd numbers is inconsistent. The subtraction operation is applied to numbers at odd indices, but the filter checks for even numbers. Please ensure that the logic aligns with the intended operation.

3. **Delimiter Issue in `split` Method**: The `split` method uses ", " as the delimiter, which assumes spaces after commas. This might not work as intended if the input does not have spaces. Consider using `","` as the delimiter to handle such cases.

4. **Input Validation in `validatePeriodsInUkraine` Method**: The method assumes the input is always in the format 'startYear-endYear'. Adding validation to ensure the input format is correct before processing will make the method more robust.

Addressing these issues will significantly improve the functionality and reliability of your code. Keep up the great work, and I'm confident you'll nail it with these adjustments! 🚀

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

🔄 Fix the issues, commit the changes, and then re-request my review using the `Re-request review` button in the Reviewers tab.

2024-11-16 20:05 UTC, mateacademy-ai-mentor commented on src/main/java/practice/CandidateValidator.java
> +    }
The `validatePeriodsInUkraine` method assumes the input is always in the format 'startYear-endYear'. If the input is malformed or does not represent a valid range, the method might not behave as expected. Consider adding validation to ensure the input format is correct before processing.

2024-11-16 20:05 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                .map(stringNum -> stringNum.split(", "))
The `split` method uses ", " as the delimiter, which assumes that the input strings have spaces after commas. If the input does not have spaces, this will not work as intended. Consider using `","` as the delimiter instead.

2024-11-16 20:05 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                .orElse(0.0);
In the `getOddNumsAverage` method, the subtraction operation is applied to numbers at odd indices, but the filter checks for even numbers. This seems inconsistent with the method's description, which mentions averaging odd numbers. Ensure that the logic aligns with the intended operation.

2024-11-16 20:05 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                        && person.getAge() >= femaleToAge))
The condition for filtering workable people seems incorrect. It should check if the person's age is less than or equal to `maleToAge` for men and `femaleToAge` for women, instead of greater than or equal to these ages.

2024-11-16 20:10 UTC, mateacademy-ai-mentor approved these changes
Thank you for your submission! 🎉 Your code has been reviewed, and while there are some issues that need attention, the decision is to **APPROVE** the Pull Request to help you move forward with your learning journey. Here are the key points to address:

1. **Logical Error in `getWorkablePeople` Method**: The filtering condition is incorrect. It should check if the person's age is less than or equal to `maleToAge` for men and `femaleToAge` for women, instead of greater than or equal to these ages.

2. **Inconsistency in `getOddNumsAverage` Method**: The method is supposed to calculate the average of odd numbers, but the filter currently checks for even numbers. Please ensure the logic aligns with the intended operation.

3. **Delimiter Issue in `findMinEvenNumber` Method**: The `split` method uses ", " as the delimiter, which assumes spaces after commas. This might not work if the input lacks spaces. Consider using `","` as the delimiter to handle such cases.

4. **Input Validation in `validatePeriodsInUkraine` Method**: While the check for `periods.length != 2` is a good start, further validation to ensure the input format is correct before processing would make the method more robust.

5. **Delimiter Issue in `split` Method**: The method assumes the input is always in the format 'startYear-endYear'. Adding validation to ensure the input format is correct before processing will enhance the method's reliability.

Please review these comments and make the necessary improvements to your code. Addressing these issues will help you avoid similar problems in the future and enhance your coding skills. Keep up the great work, and continue learning from these experiences! 🚀

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-11-16 20:10 UTC, mateacademy-ai-mentor commented on src/main/java/practice/CandidateValidator.java
> +        String[] periods = periodsInUkr.split("-");
The `split` method assumes the input is always in the format 'startYear-endYear'. Consider adding validation to ensure the input format is correct before processing.

2024-11-16 20:10 UTC, mateacademy-ai-mentor commented on src/main/java/practice/CandidateValidator.java
> +        if (periods.length != 2) {
The check for `periods.length != 2` is good, but it might be beneficial to add further validation to ensure the input format is correct before processing.

2024-11-16 20:10 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                .map(stringNum -> stringNum.split(", "))
The `split` method uses ", " as the delimiter, which assumes spaces after commas. This might not work as intended if the input does not have spaces. Consider using "," as the delimiter to handle such cases.

2024-11-16 20:10 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                .filter(i -> i % 2 == 0)
The filter checks for even numbers, but the method is supposed to calculate the average of odd numbers. Ensure that the logic aligns with the intended operation.

2024-11-16 20:10 UTC, mateacademy-ai-mentor commented on src/main/java/practice/StreamPractice.java
> +                        && person.getAge() >= femaleToAge))
The filtering condition for workable people seems incorrect. It should check if the person's age is less than or equal to `maleToAge` for men and `femaleToAge` for women, instead of greater than or equal to these ages.

2024-11-17 11:52 UTC, okuzan requested changes
Ext

2024-11-17 11:52 UTC, okuzan commented on src/main/java/practice/StreamPractice.java
> +        return modifiedNumbers.stream()
no need to collect and then stream again

2024-11-17 11:52 UTC, okuzan commented on src/main/java/practice/StreamPractice.java
> +                .filter(validator)
```suggestion

        return candidates.stream()
                .filter(new CandidateValidator())
```

2024-11-17 11:52 UTC, okuzan commented on src/main/java/practice/CandidateValidator.java
> +                candidate.getAge() >= 35,
in this class extract all literals to constants, Strings and integers

2024-11-17 16:18 UTC, VasylAzarov commented on src/main/java/practice/StreamPractice.java
> +        return modifiedNumbers.stream()
reworked

2024-11-17 16:18 UTC, VasylAzarov commented on src/main/java/practice/StreamPractice.java
> +                .filter(validator)
reworked

2024-11-17 16:18 UTC, VasylAzarov commented on src/main/java/practice/CandidateValidator.java
> +                candidate.getAge() >= 35,
done

2024-11-17 16:53 UTC, Elena-Bruyako requested changes

2024-11-17 16:53 UTC, Elena-Bruyako commented on src/main/java/practice/CandidateValidator.java
> +        ).allMatch(Boolean::booleanValue);
You can simplify it
```suggestion
        return candidate.getAge() >= MIN_CANDIDATE_AGE
                && candidate.isAllowedToVote()
                && candidate.getNationality().equals(CANDIDATE_NATIONALITY)
                && validatePeriodsInUkraine(candidate.getPeriodsInUkr());
```

2024-11-17 16:53 UTC, Elena-Bruyako commented on src/main/java/practice/StreamPractice.java
> +
```suggestion
        return numbers.stream()
                .flatMap(input -> Arrays.stream(input.split(",")))
                .map(Integer::parseInt)
                .filter(num -> num % 2 == 0)
```

2024-11-17 16:53 UTC, Elena-Bruyako commented on src/main/java/practice/StreamPractice.java
> +                .collect(Collectors.toList());
same for other places

```suggestion
                .toList();
```

2024-11-17 17:00 UTC, VasylAzarov commented on src/main/java/practice/CandidateValidator.java
> +        ).allMatch(Boolean::booleanValue);
done

2024-11-17 17:00 UTC, VasylAzarov commented on src/main/java/practice/StreamPractice.java
> +
done

2024-11-17 17:00 UTC, VasylAzarov commented on src/main/java/practice/StreamPractice.java
> +                .collect(Collectors.toList());
done

2024-11-17 17:08 UTC, Elena-Bruyako approved these changes

2025-02-09 12:50 UTC, closed without merging