Hw streams
mate-academy/jv-stream-github-practice pull request #17
Opened 2020-12-29 15:50 UTC by Likh-Alex

2020-12-29 17:30 UTC, Ketch92 requested changes

2020-12-29 17:30 UTC, Ketch92 commented on src/main/java/practice/StreamPractice.java
> +                .orElseThrow(NoSuchElementException::new);
you can you only get() it throws needed exception by default

2020-12-29 17:30 UTC, Ketch92 commented on src/main/java/practice/StreamPractice.java
> +                        && person.getAge() <= femaleToAge))
you can use the ternary operator here

2020-12-29 17:30 UTC, Ketch92 commented on src/main/java/practice/StreamPractice.java
> +                .map(cat -> cat.getName())
you can use only one map operator

2020-12-29 17:30 UTC, Ketch92 commented on src/main/java/practice/StreamPractice.java
> +                .map(candidate -> candidate.getName())
can you change the method reference?

2020-12-29 17:30 UTC, Ketch92 commented on src/main/java/practice/StreamPractice.java
> +                .mapToInt(s -> Integer.parseInt(s))
also method reference can be applied

2020-12-29 18:08 UTC, Likh-Alex commented on src/main/java/practice/StreamPractice.java
> +                .orElseThrow(NoSuchElementException::new);
Done, thank you for an idea)

2020-12-29 18:08 UTC, Likh-Alex commented on src/main/java/practice/StreamPractice.java
> +                .map(cat -> cat.getName())
Done, refactored to use one map and one flatMap

2020-12-29 18:10 UTC, Likh-Alex commented on src/main/java/practice/StreamPractice.java
> +                        && person.getAge() <= femaleToAge))
I think in this particular case ternary operator shortens the code but complicates the readability. Anyway - done, it is good to practice)

2020-12-29 18:11 UTC, Likh-Alex commented on src/main/java/practice/StreamPractice.java
> +                .map(candidate -> candidate.getName())
Done, I just liked to use lambdas as they are clearer to me)

2020-12-29 18:11 UTC, Likh-Alex commented on src/main/java/practice/StreamPractice.java
> +                .mapToInt(s -> Integer.parseInt(s))
Done, as well)

2020-12-29 19:14 UTC, Ketch92 approved these changes

2020-12-30 06:54 UTC, RomanDubovskyi approved these changes
fix message, rest seems to be good👍

2020-12-30 06:54 UTC, RomanDubovskyi commented on src/main/java/practice/StreamPractice.java
> +                .orElseThrow(() -> new RuntimeException("Can't get min value from list"));
```suggestion
                .orElseThrow(() -> new RuntimeException("Can't get min value from list: " + numbers));
```
let's make our message more informative

2020-12-30 07:53 UTC, Likh-Alex commented on src/main/java/practice/StreamPractice.java
> +                .orElseThrow(() -> new RuntimeException("Can't get min value from list"));
Done

2022-12-21 21:26 UTC, closed without merging