first commit - implemented tesks
mate-academy/jv-stream-github-practice pull request #18
Opened 2020-12-29 16:04 UTC by RuslanIbIsh

2020-12-29 16:14 UTC, less08 commented on src/main/java/practice/CandidateValidator.java
> +        return candidate.getAge() >= 35
Magic number. Вынеси число 35 в константу)

2020-12-29 16:21 UTC, less08 requested changes
Good job! But needed minor changes)

2020-12-29 16:21 UTC, less08 commented on src/main/java/practice/CandidateValidator.java
> +                && candidate.getNationality().equals("Ukrainian")
Same for String "Ukrainian"

2020-12-29 16:21 UTC, less08 commented on src/main/java/practice/CandidateValidator.java
> +        return (Integer.valueOf(datesInUkr[1]) - Integer.valueOf(datesInUkr[0])) >= 10;
Same for 10 - should be constant

2020-12-29 16:21 UTC, less08 commented on src/main/java/practice/StreamPractice.java
> +        return min.orElseThrow(() -> new RuntimeException("Can't get min value from list:"
You can add .orElseThrow right after min(). And you don`t need to create variable, write it right after return.
return numbers.stream()
```suggestion
                .min();
        return min.orElseThrow(() -> new RuntimeException("Can't get min value from list:"
```
                .map(s -> s.split(","))
                .flatMap(a -> Arrays.stream(a))
                .mapToInt(s -> Integer.parseInt(s))
                .filter(i -> i % 2 == 0)
                .min()
                .orElseThrow(() -> new RuntimeException("Message"))

2020-12-29 16:26 UTC, RuslanIbIsh commented on src/main/java/practice/CandidateValidator.java
> +        return candidate.getAge() >= 35
Thanks! Fixed

2020-12-29 16:26 UTC, RuslanIbIsh commented on src/main/java/practice/CandidateValidator.java
> +                && candidate.getNationality().equals("Ukrainian")
done

2020-12-29 16:26 UTC, RuslanIbIsh commented on src/main/java/practice/CandidateValidator.java
> +        return (Integer.valueOf(datesInUkr[1]) - Integer.valueOf(datesInUkr[0])) >= 10;
done

2020-12-29 16:32 UTC, RuslanIbIsh commented on src/main/java/practice/StreamPractice.java
> +        return min.orElseThrow(() -> new RuntimeException("Can't get min value from list:"
rewrited

2020-12-29 16:34 UTC, less08 approved these changes
Well done!

2020-12-30 06:47 UTC, RomanDubovskyi requested changes

2020-12-30 06:47 UTC, RomanDubovskyi commented on src/main/java/practice/StreamPractice.java
> +                .flatMap(a -> Arrays.stream(a))
```suggestion
               .flatMap(n -> Arrays.stream(n.split(",")))
```

2020-12-30 06:47 UTC, RomanDubovskyi commented on src/main/java/practice/StreamPractice.java
> +                        + " method_input_list"));
```suggestion
                        + numbers));
```
this way it will be more informative

2020-12-30 06:47 UTC, RomanDubovskyi commented on src/main/java/practice/StreamPractice.java
> +                        && p.getAge() >= fromAge
you can check for "fromAge" once for male and female, no need to do it twice

2020-12-30 06:47 UTC, RomanDubovskyi commented on src/main/java/practice/StreamPractice.java
> +                .flatMap(l -> l.stream())
```suggestion
                .flatMap(p -> p.getCats().stream())
```

2020-12-30 09:41 UTC, RuslanIbIsh commented on src/main/java/practice/StreamPractice.java
> +                        && p.getAge() >= fromAge
done

2020-12-30 09:42 UTC, RuslanIbIsh commented on src/main/java/practice/StreamPractice.java
> +                .flatMap(l -> l.stream())
difficult for me new but I see

2020-12-30 13:31 UTC, RomanDubovskyi approved these changes
GJ

2026-01-07 16:18 UTC, closed without merging