HomWork
mate-academy/jv-stream-github-practice pull request #287
Opened 2022-04-15 17:57 UTC by yuriikozar

Solution + Checkstyle

2022-04-18 19:15 UTC, tanya-logatskaya requested changes

2022-04-18 19:15 UTC, tanya-logatskaya commented on src/main/java/practice/StreamPractice.java
> +                .flatMap(Collection::stream)
combine to one flatMap

2022-04-18 19:15 UTC, tanya-logatskaya commented on src/main/java/practice/StreamPractice.java
> +        CandidateValidator candidateValidator = new CandidateValidator();
declare interface instance

2022-04-19 08:42 UTC, tanya-logatskaya approved these changes

2022-04-19 09:46 UTC, Sofasmile requested changes

2022-04-19 09:46 UTC, Sofasmile commented on src/main/java/practice/StreamPractice.java
> +                .stream()
```suggestion
        return numbers.stream()
```
це не помилка, але в більшості випадків `.stream()` пишуть на тому ж рядку

2022-04-19 09:46 UTC, Sofasmile commented on src/main/java/practice/StreamPractice.java
> +                .orElseThrow(NoSuchElementException::new);
```suggestion
                .getAsDouble();
```

2022-04-19 09:46 UTC, Sofasmile commented on src/main/java/practice/StreamPractice.java
> +                        && person.getSex().equals(Person.Sex.MAN))
```suggestion
                        && person.getSex() == Person.Sex.MAN)
```
єнами краще порівнювати через ==
https://stackoverflow.com/a/2937561

2022-04-19 09:46 UTC, Sofasmile commented on src/main/java/practice/StreamPractice.java
> +                        && person.getAge() >= fromAge
і для чоловіків і для жінк нижня межа віку є однаковою, давай зробимо одну перевірку замість двох

2022-04-19 10:39 UTC, Sofasmile requested changes

2022-04-19 10:39 UTC, Sofasmile commented on src/main/java/practice/StreamPractice.java
> +                .filter(person -> person.getSex().equals(Person.Sex.WOMAN)
```suggestion
                .filter(person -> person.getSex() == Person.Sex.WOMAN
```

2022-04-19 11:45 UTC, Sofasmile approved these changes

2024-02-15 18:24 UTC, closed without merging