Jv stream guthub practicemy hw
mate-academy/jv-stream-github-practice pull request #426
Opened 2022-08-25 20:28 UTC by fifahater

2022-08-25 20:53 UTC, valentyn-chepiha requested changes

2022-08-25 20:53 UTC, valentyn-chepiha commented on src/main/java/practice/StreamPractice.java
> +                .map(n -> Arrays.stream(n.split(","))
use magic value for ","

2022-08-25 20:53 UTC, valentyn-chepiha commented on src/main/java/practice/StreamPractice.java
> +                .sorted(new CandidateValidator.CandidateComparator())
```suggestion
                .sorted()
```
try without comparator

2022-08-25 20:59 UTC, fifahater commented on src/main/java/practice/StreamPractice.java
> +                .map(n -> Arrays.stream(n.split(","))
I think that putting "," into constants is not a good idea, and so from the split method it becomes clear what it is

2022-08-25 21:03 UTC, valentyn-chepiha approved these changes

2022-08-26 10:28 UTC, Sofasmile requested changes

2022-08-26 10:28 UTC, Sofasmile commented on src/main/java/practice/CandidateValidator.java
> +                - Integer.parseInt(yearLiveInUkraine[0]);
let's create constants for indexes

2022-08-26 10:28 UTC, Sofasmile commented on src/main/java/practice/StreamPractice.java
> +                .min().orElseThrow(() ->
```suggestion
                .min()
                .orElseThrow(() ->
```

2022-08-26 10:28 UTC, Sofasmile commented on src/main/java/practice/StreamPractice.java
> +        return peopleList.stream().filter(p -> p.getSex() == Person.Sex.MAN
```suggestion
        return peopleList.stream()
                    .filter(p -> p.getSex() == Person.Sex.MAN
```

2022-08-26 10:28 UTC, Sofasmile commented on src/main/java/practice/StreamPractice.java
> +                        && p.getSex() == Person.Sex.WOMAN)
better firstly check sex and then age:
```suggestion
                .filter(p -> p.getAge() >= fromAge && ((p.getSex() == Person.Sex.WOMAN
                        && p.getAge() <= femaleToAge)
```

2022-08-26 10:28 UTC, Sofasmile commented on src/main/java/practice/StreamPractice.java
> +                .collect(Collectors.toList());
same here

2022-08-26 12:09 UTC, Sofasmile approved these changes

2024-09-17 20:23 UTC, closed without merging