My solution to task stream practice
mate-academy/jv-stream-github-practice pull request #545
Opened 2022-12-27 13:08 UTC by Swyatik19

2022-12-27 15:20 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2022-12-27 15:20 UTC, Rommelua commented on src/main/java/practice/StreamPractice.java
> +                        "Can't get min value from list : Here is our inputmvn " + numbers));
```suggestion
                        "Can't get min value from list : " + numbers));
```

2022-12-27 15:20 UTC, Rommelua commented on src/main/java/practice/StreamPractice.java
> +                        && p.getSex().equals(Person.Sex.MAN))
[checklist](https://mate-academy.github.io/jv-program-common-mistakes/java-core/java-eight-part-two/stream-api#pay-attention-to-what-is-a-better-way-to-compare-enum-values-equals-vs--)
Pay attention to what is a better way to compare Enum values: equals() vs == ?

2022-12-27 19:10 UTC, Swyatik19 commented on src/main/java/practice/StreamPractice.java
> +                        "Can't get min value from list : Here is our inputmvn " + numbers));
I did not understand what is going on, what exactly to check?

2022-12-27 19:33 UTC, Rommelua commented on src/main/java/practice/StreamPractice.java
> +                        && p.getSex().equals(Person.Sex.MAN))
not fixed

2022-12-27 19:36 UTC, Rommelua requested changes
If you do not understand any mentor's comment - welcome to Slack)

2022-12-28 09:48 UTC, Swyatik19 commented on src/main/java/practice/StreamPractice.java
> +                        && p.getSex().equals(Person.Sex.MAN))
My apologies, I have already fixed everything, I just accidentally started the wrong changes

2022-12-28 11:15 UTC, Rommelua requested changes

2022-12-28 11:15 UTC, Rommelua commented on src/main/java/practice/StreamPractice.java
> +                        && p.getSex().equals(Person.Sex.MAN))
But it is still not fixed...

2022-12-28 11:15 UTC, Rommelua commented on src/main/java/practice/StreamPractice.java
> +                        && (p.getAge() <= femaleToAge && p.getSex().equals(Person.Sex.WOMAN)
and here

2022-12-28 11:38 UTC, Rommelua requested changes

2022-12-28 11:38 UTC, Rommelua commented on src/main/java/practice/StreamPractice.java
> +                .filter(p -> p.getSex().equals(Person.Sex.WOMAN) && p.getAge() >= femaleAge)
еще чуть-чуть...))))

2022-12-28 15:11 UTC, Swyatik19 commented on src/main/java/practice/StreamPractice.java
> +                .filter(p -> p.getSex().equals(Person.Sex.WOMAN) && p.getAge() >= femaleAge)
Sorry for my carelessness

2022-12-28 16:01 UTC, aaananas approved these changes

2024-03-18 17:06 UTC, closed without merging