hw-jv-stream-github-practice
mate-academy/jv-stream-github-practice pull request #690
Opened 2023-03-28 21:04 UTC by ihor-sydorenko

2023-03-29 09:31 UTC, Rommelua commented on src/main/java/practice/StreamPractice.java
> +                .flatMap(Arrays::stream)
```suggestion
                .flatMap(n -> Arrays.stream(n.split(",")))
```
![image](https://user-images.githubusercontent.com/20326858/228491647-6f830e95-7a84-41d2-aba1-6fcdad75b21a.png)

2023-03-29 09:36 UTC, Rommelua commented on src/main/java/practice/StreamPractice.java
> +                .filter(person -> person.getSex().equals(Person.Sex.MAN)
![image](https://user-images.githubusercontent.com/20326858/228492783-58318bc6-a0c0-469a-9be4-773cbac3e126.png)

2023-03-30 19:32 UTC, aaananas requested changes

2023-03-30 19:32 UTC, aaananas commented on src/main/java/practice/CandidateValidator.java
> +                - Integer.parseInt(splitDatePeriod[0]);
add constants for indexes

2023-03-30 19:32 UTC, aaananas commented on src/main/java/practice/StreamPractice.java
> +                .flatMap(Collection::stream)
```suggestion
                .flatMap(person -> person.getCats().stream())
```

2023-03-31 09:20 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and **correct all the points** described there. The mentor will not check the work until the checklist points are corrected

2023-03-31 09:20 UTC, Rommelua commented on src/main/java/practice/StreamPractice.java
> +                        || person.getSex().equals(Person.Sex.WOMAN)
You still have this mistake(((
![image](https://user-images.githubusercontent.com/20326858/229080110-6df01421-87a0-4783-bf20-3d9b1b5b0008.png)

2023-04-02 09:21 UTC, Rommelua approved these changes

2024-12-20 15:37 UTC, closed without merging