implemented task from README.md
mate-academy/jv-stream-github-practice pull request #806
Opened 2023-07-27 13:53 UTC by Denis-Balako

2023-07-27 15:16 UTC, holsoni requested changes
Very nice implementation!

2023-07-27 15:35 UTC, Denis-Balako commented on src/main/java/practice/StreamPractice.java
> +                .orElseThrow();
https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/OptionalDouble.html#orElseThrow()

2023-07-27 15:38 UTC, holsoni approved these changes
Super cool!!🎉

2023-07-28 07:52 UTC, nacenik approved these changes
Good solution, but I'd recommend you create an anonymous predicate instead of the class predicate with parameter `Map<String, integer>`

2023-07-28 07:52 UTC, nacenik commented on src/main/java/practice/StreamPractice.java
> +                .orElseThrow();
See what `getAsDouble()` does

2026-05-02 16:41 UTC, closed without merging