stream functions
mate-academy/jv-stream-github-practice pull request #822
Opened 2023-07-28 11:42 UTC by ConfusedSatlan

2023-07-28 14:04 UTC, irynamekh requested changes

2023-07-28 14:04 UTC, irynamekh commented on src/main/java/practice/CandidateValidator.java
> +        return false;
write like this, you don't need if
return countYearInUkr >= 10 (magic num)

2023-07-28 14:04 UTC, irynamekh commented on src/main/java/practice/StreamPractice.java
> +
you have many redundant empty lines

2023-07-28 17:34 UTC, irynamekh approved these changes

2023-07-31 08:49 UTC, Vasul-Pankiv requested changes

2023-07-31 08:49 UTC, Vasul-Pankiv commented on src/main/java/practice/StreamPractice.java
> +
not resolved

2023-07-31 08:49 UTC, Vasul-Pankiv commented on src/main/java/practice/StreamPractice.java
> +                    if (i % MOD_NUM_CHECK != ZERO_NUM) {
```suggestion
                    if (i % MOD_NUM_CHECK != ZERO_NUM) {
```
"i % MOD_NUM_CHECK" extract it to method and reuse

2023-07-31 10:47 UTC, Vasul-Pankiv approved these changes

2024-04-22 11:03 UTC, closed without merging